

services: 
  mysql:
    image: mysql:latest
    container_name: trabajoYML
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "biblioteca"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports: 
      - "3310:3306"
    volumes: 
      - "mysql_db:/var/lib/mysql"
      - "./bd.sql:/docker-entrypoint-initdb.d/bd.sql"

volumes:
  mysql_db:
